language: ruby
rvm:
- 2.2.3

# deploy:
#   provider: rubygems
#   api_key:
#     secure: 9366a5792327ea3ee44371e8a625aaf8
#   gem: sinatra-app-test
#   on:
#     tags: true
#     all_branches: true
#
# env:
#   global:
#   - secure: T8L84sWENsNlck2SGTUOmB1OKsJRiam0jsUIXi0QhGlAPSP92h1WvpohixBtbp8FpaPqsG9YSwKj20VzauqwnEWkbtv0Yu9tfjJwWIvlZwdJHRp1KBRs4HeOlOiX6HEv1a0ahBp0pOK3jLojoDfxiqHU8H7B4GhKw0f5G0vkUvc=
#   - secure: KulQLPiNqmJ8G56N1bSmbVH0e8r58tGstKv7lgPKHH7aLSskZpOzi4aC2jQJMcCti6vsbWORQuwRyhlG8v/iLbYYdrPquf46mQOIjkJ7i/qOnAOfaomMo2jJso/w7/dtvjH2DkCWelTdhx7HKU8TRF0xjBdO6omWVi7RqmZokhE=
#
# after_success:
# - coveralls
# - '[ "${TRAVIS_BRANCH}" = "master" ] && git tag v${TRAVIS_BUILD_NUMBER} && git push -f https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${TRAVIS_REPO_SLUG}.git --tags'
