install: true
sudo: required
dist: trusty

env:
  global:
    - RANCHER_COMPOSE_VERSION=0.8.6
    - DEPLOY=false

before_install:
  # make sure we get the #deployuat for the pull request merge
  - $((git log -n 1 | grep -q 'Merge' && git log -n 2 | grep -q '#deployuat') || $(git log -n 1 | grep -q '#deployuat')); DEPLOY_UAT=$?

script:
  echo $DEPLOY_UAT

after_success:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $DEPLOY_UAT

  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "MASTER BRANCH";
    fi

  - if [ $DEPLOY_UAT -eq 0 ] && [ "$TRAVIS_BRANCH" != "master" ]; then
    export DEPLOY=true;
    echo "AFTER SUCCESS DO DEPLOY";
    fi

before_deploy:
  - test $DEPLOY = true
    && sudo apt-get -qq update
    && sudo apt-get install -y tar
    && wget https://github.com/rancher/rancher-compose/releases/download/v$RANCHER_COMPOSE_VERSION/rancher-compose-linux-amd64-v$RANCHER_COMPOSE_VERSION.tar.gz -O rancher-compose.tar.gz
    && tar zxvf rancher-compose.tar.gz --strip-components 2
    && rm -rf rancher-compose.tar.gz
    && sudo mv rancher-compose /usr/bin/rancher-compose
    && sudo chmod +x /usr/bin/rancher-compose
    && rancher-compose -v

  - echo "user = \"$ACCESS_KEY:$SECRET_KEY\"" | curl -K - https://google.com
  - ls -la
deploy:
  provider: script
  skip_cleanup: true
  on:
    condition: $DEPLOY = true
    all_branches: true
  script: echo "DEPLOYING"
