install: true
sudo: required
dist: trusty

env:
  global:
    - RANCHER_COMPOSE_VERSION=0.8.6
    - "DEPLOY=false"

script:
  echo "SUCCESS";

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "NOT DOING ANYTHING";
    fi

  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    export DEPLOY=true;
    echo "AFTER SUCCESS DO DEPLOY";
    fi

before_deploy:
  - test $DEPLOY = true
    && sudo apt-get -qq update
    && sudo apt-get install -y tar
    && wget https://github.com/rancher/rancher-compose/releases/download/v$RANCHER_COMPOSE_VERSION/rancher-compose-linux-amd64-v$RANCHER_COMPOSE_VERSION.tar.gz -O rancher-compose.tar.gz
    && tar zxvf rancher-compose.tar.gz --strip-components 2
    && rm -rf rancher-compose.tar.gz
    && sudo mv rancher-compose /usr/bin/rancher-compose
    && sudo chmod +x /usr/bin/rancher-compose
    && rancher-compose -v
  
  - echo "login $(ACCESS_KEY) password $(SECRET_KEY)" > auth
  - curl -s -L --netrc-file auth http://google.com -o config.zip
  - ls -la
deploy:
  provider: script
  skip_cleanup: true
  on:
    condition: $DEPLOY = true
    all_branches: true
  script: echo "DEPLOYING"
